sudo: false
language: python
python: "3.5"
cache:
  directories:
    - "$HOME/.tox"
before_cache:
  - rm -f $HOME/.tox/$TOXENV/log/*.log
env:
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=flake8
  - TOXENV=mypy
matrix:
  include:
    - python: "3.6-dev"
      env: TOXENV=py36
install:
  - pip install -q tox coveralls
  - pip install -q -r requirements/general.txt
script:
  - tox
after_success:
  - coverage run --source=kobin setup.py test
  - coveralls
